---
sabnzbd:
    build: .
    container_name: sabnzbd
    volumes:
        - ./data/datadir:/datadir
        - ./data/download:/download
        - ./data/media:/media
    restart: always
    ports:
        - "8080:8080"
